name: Deployment pipeline

on:
  push:
    branches:
      - main


jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: part11/pokedx

      - name: Check style
        run: npm run eslint
        working-directory: part11/pokedx